## 2 Solving Simple Linear Models

In [1]:
#Let's solve the most basic IS-LM model for a closed economy

#Note: we can import packages in different ways
#This is the standard way
import numpy as np
#This is an alternative way that allows to use more compact commands
from scipy.linalg import inv, solve, det

#Assign the appropriate values to the matrix of coefficients A
#Notice that we are using round brackets: in principle this makes the matrix immutable
A = ((1, 0.0005),
     (1, -0.00025))

#Check that it is a matrix and not a list (which is a collection of mutable objects, and use square brackets)
type(A)

tuple

In [2]:
a_tuple = ("apple", "banana", "cherry")
print(a_tuple)

('apple', 'banana', 'cherry')


In [3]:
#Assign the appropriate values to the vector of constants b
b = (0.55, -0.2)

#Check that it is a vector
type(b)

tuple

In [4]:
#Change the type of the matrix to allow changes in its entries
A = np.array(A)

#Check that it is a matrix
#Most linear algebra operations work with both tuples and arrays
type(A)

numpy.ndarray

In [5]:
#Check that A is non-singular, hence invertible
#Note the simple syntax, namely without the need to type "scipy.linalg.det(A)"
det(A)

#Not used
#b = np.array(b)
#b=b.T #Column vector

-0.00075

In [6]:
#Compute and display the inverse
A_inv = inv(A)
A_inv

array([[ 3.33333333e-01,  6.66666667e-01],
       [ 1.33333333e+03, -1.33333333e+03]])

In [7]:
#Compute the solution to the system of two linear equations
x = np.dot(A_inv, b)

x

array([5.e-02, 1.e+03])

In [8]:
#Check that the solution is correct (the multiplication A*x should equal b)
np.dot(A, x)

array([ 0.55, -0.2 ])

In [9]:
#If we wanted to change the first entry in the matrix we could type
A[0,0] = 2

In [10]:
#Let's check that we are working with the updated matrix
A

array([[ 2.0e+00,  5.0e-04],
       [ 1.0e+00, -2.5e-04]])

In [11]:
#If we wanted to change the first entry in the vector we could type
#This prompts an error as b is immutable
b[0]=0.5

TypeError: 'tuple' object does not support item assignment

In [12]:
#Wrapping up:
# -lists use square brackets and allow the programmer to change their values
# -tuples use round brackets and do not allow the programmer to change their values (can prevent "user error")

In [13]:
#Assign the appropriate values to the (3x3) matrix of coefficients Anew
Anew = [(0, 1, 0),
     (1, 0.0005, 0),
     (1, -0.00025, 0.2)]

#The type
type(Anew)

list

In [14]:
#Assign the appropriate values to the vector of constants b
bnew = [1000, 0.55, 0]

#Check that it is a vector
type(bnew)

list

In [15]:
#Check that Anew is non-singular, hence invertible
det(Anew)

-0.2

In [16]:
#Compute the inverse
Anew_inv = inv(Anew)

In [17]:
#Compute the solution to the system of three linear equations
xnew = np.dot(Anew_inv, bnew)

xnew

array([5.e-02, 1.e+03, 1.e+00])

In [18]:
#Compute the equilibrium price level
P=1/xnew[2]

P

1.0